### ISSUE TITLE
Having problem with preprocess_webnlg.py

### ISSUE THREAD

**Issue by Almazick** [MathewAlexander/T5_nlg#1]
Having problem with preprocess_webnlg.py.  It generates a blank file using https://gitlab.com/shimorina/webnlg-dataset/-/tree/master/release_v3.0/en/train files.  Any advice?

**Comment by MathewAlexander** [comment]
Hi @Almazick 
Could you please elaborate on the problem?. I am looking for details like which line of code is causing the issue etc.

**Comment by vishal-22** [comment]
While running the preprocess_webnlg.py to generate csv it gives a blank file with no data.

**Comment by harshhp8** [comment]
> While running the preprocess_webnlg.py to generate csv it gives a blank file with no data.

Have you got any solution? @MathewAlexander can you provide updated preprocessing file.

**Comment by vishal-22** [comment]
> > While running the preprocess_webnlg.py to generate csv it gives a blank file with no data.
> 
> Have you got any solution? @MathewAlexander can you provide updated preprocessing file.

No solution so far. Waiting @MathewAlexander to provide necessary updates.

**Comment by MathewAlexander** [comment]
@harshhp8 @vishal-22 @Almazick 
Updated the script, Please check now.
Let me know if you run into any other issues.

**Comment by harshhp8** [comment]
@MathewAlexander No need to update.It is working fine.Problem was in path.
`files = glob.glob("G:/Movies/webnlg-dataset-master-release_v3.0/webnlg-dataset-master-release_v3.0/release_v3.0/en/train/**/*.xml", recursive=True)`

i have given absolute path and its working fine.
@vishal-22

**Comment by MathewAlexander** [comment]
@harshhp8 
Yeah, it was just a matter of providing the path correctly.
To avoid confusion, I changed it to a self-containing script that would download the data and do all the processing.
Feel free to re-open if the issue persists.
