### ISSUE TITLE
Generated text length 

### ISSUE THREAD

**Issue by hamdi3** [MathewAlexander/T5_nlg#4]
Hello Mathew,
I've realized while using T5 model that the generated texts are being cut off, and I've seen that you've had the same issue with some sentences at the end of your Notebook.
I wonder if there was a solution for this or if it was an issue with the T5.
If there was one, I'd be thankful if you could fix your code or share it !

**Comment by jackhax** [comment]
> Hello Mathew, I've realized while using T5 model that the generated texts are being cut off, and I've seen that you've had the same issue with some sentences at the end of your Notebook. I wonder if there was a solution for this or if it was an issue with the T5. If there was one, I'd be thankful if you could fix your code or share it !

You can specify the maximum output length by providing max_length parameter to generator method.

`
model.generate(input_ids,max_length=512)
`

This is defaulted to 20 tokens.
